name: ci workflow for grpccoooooonnpool

on:
  push:
    branches:
      - main
      - master
      - releases/*
  pull_request:
    branches:
      - main
      - master
      - releases/*

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.11
      - name: Lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.41.1
      - name: Build
        run: go build /home/runner/work/grpccoooooonnpool/grpccoooooonnpool/mocker/mock-proxy